### PR TITLE
Make it into a more standard python package

### PR DESCRIPTION
**Pull request by michaelboulton**
I just added a setup.py and shuffled the files around so that it can be installed as a package via pip/setuptools.

eg:

`pip install git+https://github.com/michaelboulton/debinterface.git`

### CODE REVIEW

**Comment by nMustaki** [comment]
Many thanks !
Have you rerun the tests ?

**Comment by michaelboulton** [comment]
Running `python setup.py test`:

```
running test
running egg_info
writing debinterface.egg-info/PKG-INFO
writing top-level names to debinterface.egg-info/top_level.txt
writing dependency_links to debinterface.egg-info/dependency_links.txt
reading manifest file 'debinterface.egg-info/SOURCES.txt'
writing manifest file 'debinterface.egg-info/SOURCES.txt'
running build_ext
test_backup (test.test_hostapd.TestHostapd) ... ok
test_read (test.test_hostapd.TestHostapd) ... ok
test_restore (test.test_hostapd.TestHostapd) ... ok
test_validate_valid (test.test_hostapd.TestHostapd)
Test validate with valid data ... ok
test_write (test.test_hostapd.TestHostapd) ... ok
test_backup (test.test_dnsmasqRange.TestDnsmasqRange) ... ok
test_extract_range_info (test.test_dnsmasqRange.TestDnsmasqRange) ... ok
test_read (test.test_dnsmasqRange.TestDnsmasqRange) ... ok
test_restore (test.test_dnsmasqRange.TestDnsmasqRange) ... ok
test_set (test.test_dnsmasqRange.TestDnsmasqRange)
Test set dhcp-range ... ok
test_set_multiple_times (test.test_dnsmasqRange.TestDnsmasqRange)
Test set dhcp-range with many times the same value ... ok
test_update_range (test.test_dnsmasqRange.TestDnsmasqRange) ... ok
test_validate_invalid_ip (test.test_dnsmasqRange.TestDnsmasqRange)
Test validate with false data ... ok
test_validate_valid (test.test_dnsmasqRange.TestDnsmasqRange)
Test validate with valid data ... ok
test_write (test.test_dnsmasqRange.TestDnsmasqRange) ... ok
test_dnsnameservers_not_unknown (test.test_interfacesReader.TestInterfacesReader)
All adapters should validate ... ok
test_parse_interfaces (test.test_interfacesReader.TestInterfacesReader)
All adapters should validate ... ok
test_parse_interfaces_count (test.test_interfacesReader.TestInterfacesReader)
Should have 8 adapters ... ok

----------------------------------------------------------------------
Ran 18 tests in 0.016s

OK
```

Should be OK!

**Comment by nMustaki** [comment]
I'll push it to pypi tonight, thanks to you, thanks again !

**Comment by michaelboulton** [comment]
You might want to add the author/author email/etc lines into the call to setup(), I just left them blank deliberately.

**Comment by nMustaki** [comment]
I'll add a contributors.md file too


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Pull request merged**
