### PR TITLE
Add ability to provide header comments, added parsing of 'dns-search'

### PR DESCRIPTION
**Pull request by mikeodr**
Added param to InterfacesWriter to add the ability to publish a commented text string at the beginning of the interfaces file.

### CODE REVIEW

**Comment by nMustaki** [comment]
Hi !
many thanks, that's a nice idea !
I have two nitpicks:
- InterfaceWriter.writeInterfaces : should be passed the comments
- How can be the comments be read back from file ?

**Comment by mikeodr** [comment]
I can look to address your comments shortly.

Thanks for the feedback.

**Comment by mikeodr** [comment]
I think you meant `Interfaces.writeInterfaces()` needed to pass the comments? If that's not the case please let me know as I've added that.

I've added what I think to be a backwards compatible way to return both adapters and comments from the `InterfaceReader.parse_interfaces()` function. Along with some new unit tests to check the parsing.

I'm open to suggestions on either part.

**Comment by nMustaki** [comment]
That sounds great, many thanks !
I'll have a real look tonight

**Comment by nMustaki** [comment]
So, I think it's not wise to change the return of parse_interfaces, as it's too easy to break existing code. The safer way is to access comments only through the property.
Since this library could be brick a computer, I am not keen on taking risks !
Let me know if you want to change back the parse_interfaces() function, or I'll do it.
Thanks again !

**Comment by mikeodr** [comment]
I'll update it, and I concur. Was wanting your feedback on that path.

**Comment by mikeodr** [comment]
Added one last test for a file with no comments at the top.

**Comment by mikeodr** [comment]
I've added another commit to this PR to allow for strict ordering of `dns-search` option after the `dns-namerservers` entry. Was using this as an "other" option and my unit tests for another project were seeing spurious failures due to dict-order parsing for "other" options fields.

**Comment by nMustaki** [comment]
Nice catch, thanks!
It's been hectic at work lately but I promess I'll promess I'll release soon

**Comment by mikeodr** [comment]
I Can relate. Not a problem at all!

**Comment by mikeodr** [comment]
Happy new year, just a soft check in on getting this merged.

No panic if not, I'm still running it off my branch as a zip install.

**Comment by nMustaki** [comment]
Happy new year too !
I promise I'm deploying it next week, it's been really too long sorry !


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by nMustaki** [comment]
Finally is is deployed ! Thanks for your patience ;-)
I've fixed a bug where comments given to the Interfaces class were not saved in the class attribute, your fork may have the same issue ?

**Comment by mikeodr** [comment]
@nMustaki thank you very much for the merge, much appreciated.

**Comment by mikeodr** [comment]
I see it here: https://github.com/nMustaki/debinterface/commit/f0f2d85443b62e05224248e74ac8fd14f9437bc5

Good catch.

**Pull request merged**
