### PR TITLE
Support ipv6, dns-*, source and more hooks

### PR DESCRIPTION
**Pull request by t-tran**
Requested by @nMustaki here:
https://github.com/dggreenbaum/debinterface/pull/10#issuecomment-263109807

### CODE REVIEW

**Comment by nMustaki** [comment]
Many thanks !
I'll take in the latest commits, they are great additions !

**Comment by gaby** [comment]
@nMustaki Any plans to merge this or update this library?

**Comment by nMustaki** [comment]
Hi @gaby yes that would be great, it's a nice PR ! I completly forgot about it and there are a lot of conflicts, but I'll try to merge it soon.
Once it's done, would do be willing to test it on your side ?

**Comment by nMustaki** [comment]
I'm closing that one, I finaly created a mergeable PR from this one (https://github.com/nMustaki/debinterface/pull/36)

@gaby would you mind testing it ?

**Comment by gaby** [comment]
@nMustaki I can take a look

**Pull request closed without merging**
